version: "3.3"
services:
# app name
  nodejs-app:
    container_name: node-app-container
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


