version: "3.3"
services:
  nodejs-app:
    volumes:
        - .:/app
        - ./.env:/app/.env
        - ./views:/app/views
        - ./src:/app/src
    build:
        context: .
    ports:
      - "3000:3000"
      - "3001:3001"



