version: "3.3"
services:
# app name
  nodejs-app:
    container_name: node-app-container
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    # app name
  mongodb:
    image: mongo
    container_name: mongodb-container
    volumes:
        - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=nodejs-app
volumes:
  mongodb: