version: "3.3"
services:
# app name
  nodejs-app:
  # container name when running and building
    container_name: node-app-container
    build: .
    # the image to use
    volumes:
      - ./src:/app/src:ro
      - ./views:/app/views:ro
    # ports to expose
    ports:
      - "3000:3000"
      - "3001:3001"
    # environment variables
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - ./.env


